# Use Docker-based container (instead of OpenVZ)
sudo: false

cache:
  directories:
    - $HOME/.ivy2/cache

    # At the moment, sbt 0.13.5 is preinstalled in Travis VM image,
    # which fortunately corresponds to current scalaz settings.
    # The line below can be used to cache a given sbt version.
    # - $HOME/.sbt/launchers/0.13.x

    # At the moment, Scala 2.11.2 and 2.10.4 are preinstalled in Travis VM
    # image, which fortunately corresponds to current scalaz settings.
    # The line below is used to cache the scala version used by the build
    # job, as these versions might be replaced after a Travis CI build
    # environment upgrade (e.g. scala 2.11.2 could be replaced by scala 2.11.4).
    - $HOME/.sbt/boot/scala-$TRAVIS_SCALA_VERSION

language: scala
scala:
  - 2.11.7
  - 2.10.6
jdk:
  - openjdk7

script:
  - sbt ++$TRAVIS_SCALA_VERSION -J-Xmx3784m test

  # Tricks to avoid unnecessary cache updates
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm

matrix:
  include:
    - scala: 2.12.0-M3
      jdk: oraclejdk8

addons:
  apt:
    packages:
      - oracle-java8-installer

# Use PhantomJS 2
# https://mediocre.com/forum/topics/phantomjs-2-and-travis-ci-we-beat-our-heads-against-a-wall-so-you-dont-have-to
install:
  - mkdir travis-phantomjs
  - wget https://s3.amazonaws.com/travis-phantomjs/phantomjs-2.0.0-ubuntu-12.04.tar.bz2 -O "$PWD"/travis-phantomjs/phantomjs-2.0.0-ubuntu-12.04.tar.bz2
  - tar -xvf "$PWD"/travis-phantomjs/phantomjs-2.0.0-ubuntu-12.04.tar.bz2 -C "$PWD"/travis-phantomjs
  - export PATH="$PWD/travis-phantomjs:$PATH"

