# Use Docker-based container (instead of OpenVZ)
sudo: false

cache:
  directories:
    - $HOME/.ivy2/cache

    # At the moment, sbt 0.13.5 is preinstalled in Travis VM image,
    # which fortunately corresponds to current scalaz settings.
    # The line below can be used to cache a given sbt version.
    # - $HOME/.sbt/launchers/0.13.x

    # At the moment, Scala 2.11.2 and 2.10.4 are preinstalled in Travis VM
    # image, which fortunately corresponds to current scalaz settings.
    # The line below is used to cache the scala version used by the build
    # job, as these versions might be replaced after a Travis CI build
    # environment upgrade (e.g. scala 2.11.2 could be replaced by scala 2.11.4).
    - $HOME/.sbt/boot/scala-$TRAVIS_SCALA_VERSION

language: scala
scala:
  - 2.12.0-M3
  - 2.11.8
  - 2.10.6
jdk:
  - oraclejdk8 # scalaz 7.3 does not support Java 7

script:
  - sbt ++$TRAVIS_SCALA_VERSION -J-Xmx3784m check-gen-type-classes "project $TEST_PROJECT" test:compile
  - sbt ++$TRAVIS_SCALA_VERSION "project $TEST_PROJECT" test "project /" $(if [[ "${TEST_PROJECT}" == "rootJVM" ]]; then echo "publish" ; fi)
  # Tricks to avoid unnecessary cache updates
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm

env:
  matrix:
  - TEST_PROJECT="rootJVM"
  - TEST_PROJECT="rootJS"
  global:
  - secure: ofDZjMTk4IvQe4erz0/3ib0b8uuaSaUIzS5BLvrTOa3ejPaEeEX39cKJ2HEtXhfKmC+BZJiF9qKK77Kvot2r65IRpY7LSggPUrYjkxGUyAOAv649miWRK/UkArwkFKAzsNANtH2nY1wtb9lyIP5F5DyohqS0Iox4H9v6GdTD914=
  - secure: VvFXtr6UE8ekSuBWECXJsOGx6NbJOIosgFNj2yOxpRkBTC5M+mA9CBvOPO9a7A6/U6NTNabbk1bGdSOnuu4rTEst4kHqWCAMh3mvMHLN8NRTq6FTCr8iy8WHOgLx28DWGdkG3PBd9zfzfoRZ3PLClyNFqMLDIes8NVDjx2zuN3E=

addons:
  apt:
    packages:
      - oracle-java8-installer
