language: scala
scala:
  - 2.11.0
  - 2.10.4
jdk:
  - oraclejdk7

script:
  - sbt ++$TRAVIS_SCALA_VERSION clean core/update core/compile
  - sbt ++$TRAVIS_SCALA_VERSION clean core/update core/compile
  - sbt ++$TRAVIS_SCALA_VERSION clean core/update core/compile
  - sbt ++$TRAVIS_SCALA_VERSION clean core/update core/compile
  - sbt ++$TRAVIS_SCALA_VERSION clean core/update core/compile
  - sbt ++$TRAVIS_SCALA_VERSION clean core/update core/compile
  - sbt ++$TRAVIS_SCALA_VERSION clean core/update core/compile

