# Use Docker-based container (instead of OpenVZ)
sudo: false

cache:
  directories:
    - $HOME/.ivy2/cache

language: scala
scala:
  - 2.11.7
  - 2.10.5
  - 2.9.2
  - 2.9.3
jdk:
  - oraclejdk7
  - openjdk6

script:
  - sbt ++$TRAVIS_SCALA_VERSION -J-Xmx3784m test mima-report-binary-issues
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm

matrix:
  include:
    - scala: 2.12.0-M3
      jdk: oraclejdk8
      script: sbt ++$TRAVIS_SCALA_VERSION -J-Xmx3784m test && rm -rf $HOME/.ivy2/cache
