# Use Docker-based container (instead of OpenVZ)
sudo: false

cache:
  directories:
    - $HOME/.ivy2/cache

language: scala
scala:
  - 2.11.5
  - 2.10.4
  - 2.9.2
  - 2.9.3
jdk:
  - oraclejdk7
  - openjdk6

script:
  - sbt ++$TRAVIS_SCALA_VERSION -J-Xmx3784m test mima-report-binary-issues publish
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm

env:
  global:
  - secure: ofDZjMTk4IvQe4erz0/3ib0b8uuaSaUIzS5BLvrTOa3ejPaEeEX39cKJ2HEtXhfKmC+BZJiF9qKK77Kvot2r65IRpY7LSggPUrYjkxGUyAOAv649miWRK/UkArwkFKAzsNANtH2nY1wtb9lyIP5F5DyohqS0Iox4H9v6GdTD914=
  - secure: VvFXtr6UE8ekSuBWECXJsOGx6NbJOIosgFNj2yOxpRkBTC5M+mA9CBvOPO9a7A6/U6NTNabbk1bGdSOnuu4rTEst4kHqWCAMh3mvMHLN8NRTq6FTCr8iy8WHOgLx28DWGdkG3PBd9zfzfoRZ3PLClyNFqMLDIes8NVDjx2zuN3E=
