language: scala
scala:
  - 2.11.0
  - 2.10.4
  - 2.10.3
  - 2.10.2
  - 2.10.1
  - 2.10.0
  - 2.9.3
  - 2.9.2
jdk:
  - oraclejdk7

script:
  - sbt ++$TRAVIS_SCALA_VERSION clean core/update core/compile
  - sbt ++$TRAVIS_SCALA_VERSION clean core/update core/compile
  - sbt ++$TRAVIS_SCALA_VERSION clean core/update core/compile
  - sbt ++$TRAVIS_SCALA_VERSION clean core/update core/compile
  - sbt ++$TRAVIS_SCALA_VERSION clean core/update core/compile
  - sbt ++$TRAVIS_SCALA_VERSION clean core/update core/compile
  - sbt ++$TRAVIS_SCALA_VERSION clean core/update core/compile

